# Employee Table insertion after check all cleaning things

INSERT INTO silver.employee (
  employeeid,
  firstname,
  lastname,
  gender,
  age,
  businesstravel,
  department,
  "DistanceFromHome (KM)",
  state,
  ethnicity,
  education,
  educationfield,
  jobrole,
  maritalstatus,
  salary,
  stockoptionlevel,
  overtime,
  hiredate,
  attrition,
  yearsatcompany,
  yearsinmostrecentrole,
  yearssincelastpromotion,
  yearswithcurrmanager,
  created_at
)
SELECT 
  employeeid,
  firstname,
  lastname,
  gender,
  age,
  businesstravel,
  department,
  "DistanceFromHome (KM)",
  state,
  ethnicity,
  education,
  educationfield,
  jobrole,
  maritalstatus,
  salary,
  stockoptionlevel,
  overtime,
  hiredate,
  attrition,
  yearsatcompany,
  yearsinmostrecentrole,
  yearssincelastpromotion,
  yearswithcurrmanager,
  CURRENT_TIMESTAMP
FROM bronze.employee;
